databases:
  - name: daftpunk
    databaseName: daftpunk
    user: daftpunk

services:
  - type: web
    name: daftpunk
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: daftpunk
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
